version: "3.7"
services:
  
  jellyfin:
    container_name: jellyfin
    image: cr.hotio.dev/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/India
    network_mode: host
    volumes:
      - D:\Docker\Appdata\Jellyfin:/config
      - D:\Media\Media:/data  
    restart: unless-stopped

