services:

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - UMASK=002
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - D:\Docker\Appdata\Qbit:/config
      - D:\Media\Torrents:/data  
    network: 
      - proxynet

networks:
  proxynet:
    external:
      name: custom_network


